import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHero } from "@/components/school/PageHero";
import { Reveal } from "@/components/school/Reveal";
import { clubs, programmes } from "@/lib/site-content";

export const Route = createFileRoute("/academics")({ head: () => ({ meta: [
  { title: "Academics — Annointed comprehensive high school" }, { name: "description", content: "Explore creche, nursery, primary and secondary learning at Annointed comprehensive high school in Uyo." },
  { property: "og:title", content: "Academics at Annointed comprehensive high school" }, { property: "og:description", content: "Strong foundations, curious minds and practical learning at every stage." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AcademicsPage });

const subjects = ["English Language", "Mathematics", "Basic Science", "Social Studies", "ICT & Digital Skills", "Creative Arts", "Civic Education", "Religious Studies"];

function AcademicsPage() { return <>
  <PageHero eyebrow="Learning at RGGA" title="Strong foundations. Curious minds." intro="Our academic journey combines clear instruction, active discovery and steady encouragement so learners can understand deeply, think independently and express themselves well." />
  <section className="section-pad"><div className="page-shell"><Reveal className="max-w-2xl"><p className="eyebrow text-primary">Three learning stages</p><h2 className="section-title mt-4">A thoughtful path from first steps to future plans.</h2></Reveal><div className="mt-12 grid gap-5">{programmes.map(({ title, ages, description, icon: Icon, accent }, index) => <Reveal key={title} className="academic-row"><div className={`programme-icon ${accent}`}><Icon /></div><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted-foreground">Stage 0{index + 1} · {ages}</p><h3 className="mt-2 font-display text-3xl text-primary">{title}</h3></div><p className="text-sm leading-7 text-muted-foreground">{description} Learning details are illustrative and will be aligned with the school's confirmed curriculum.</p></Reveal>)}</div></div></section>
  <section className="section-pad bg-soft"><div className="page-shell grid gap-10 lg:grid-cols-2"><Reveal><p className="eyebrow text-primary">How we teach</p><h2 className="section-title mt-4">Understand. Practise. Apply.</h2><p className="mt-6 leading-8 text-muted-foreground">Each topic moves from clear explanation to guided practice and meaningful application. Teachers check understanding often and adapt support so no learner becomes invisible.</p><div className="mt-7 grid gap-3">{["Clear learning goals", "Practical and project-based activities", "Regular feedback and family communication", "Support and stretch for different learning needs"].map((item) => <p key={item} className="flex gap-3 text-sm font-semibold"><CheckCircle2 className="h-5 w-5 shrink-0 text-gold-deep" />{item}</p>)}</div></Reveal><Reveal className="subject-panel"><p className="eyebrow text-gold">Illustrative subjects</p><div className="mt-6 grid grid-cols-2 gap-px overflow-hidden rounded-md bg-primary-foreground/15">{subjects.map((subject) => <div key={subject} className="bg-primary p-4 text-sm text-primary-foreground/80">{subject}</div>)}</div></Reveal></div></section>
  <section className="section-pad"><div className="page-shell"><Reveal className="text-center"><p className="eyebrow text-primary">Beyond the timetable</p><h2 className="section-title mt-4">Discover talents. Build confidence.</h2></Reveal><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{clubs.map(({ name, icon: Icon }) => <Reveal key={name} className="club-tile"><Icon /><span>{name}</span></Reveal>)}</div><div className="mt-12 flex justify-center"><Button asChild size="lg"><Link to="/admissions">Ask about a programme <ArrowRight /></Link></Button></div></div></section>
</>; }